apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: myapp
    type: frontend
spec:
  selector:
    app: myapp
  type : LoadBalancer
  ports:
  - targetPort: 80
    port : 80
    nodePort: 30008
